# Generated by Django 6.0.6 on 2026-07-06 18:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the image.', max_length=255)),
                ('image', models.ImageField(help_text='The uploaded image file.', upload_to='annotated_images/')),
                ('polygons', models.JSONField(blank=True, default=core.models.default_polygons, help_text='List of polygons, where each polygon is represented by an array of coordinate objects or numbers.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the task.', max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='The priority level of the task.', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('done', 'done')], default='todo', help_text='The kanban status of the task.', max_length=20)),
                ('due_date', models.DateField(help_text='The due date of the task.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags represented as JSON array of strings.')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
