# Generated by Django 6.0.6 on 2026-07-07 12:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='annotatedimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='annotatedimage',
            name='image',
            field=models.ImageField(upload_to='annotated_images/'),
        ),
        migrations.AlterField(
            model_name='annotatedimage',
            name='polygons',
            field=models.JSONField(default=core.models.default_polygons),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
